[General]
# 通用设置

# > TLS 引擎
tls-provider = openssl

# > Custom GeoIP database
geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

# > IPv6 support (off by default)
ipv6 = false

# > Allow Wifi access (iOS only, if remote access is allowed, change "false" to "true")
allow-wifi-access = false
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153

# > Compatibility mode (iOS only)
# compatibility-mode = 0
# > Skip proxy
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, passenger.t3go.cn
# > Exclude simple hostnames
exclude-simple-hostnames = true

internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
proxy-test-udp = cp.cloudflare.com@1.1.1.1
test-timeout = 3

# > DNS Server
dns-server = 1.0.0.1,8.8.8.8,system
# > Read DNS records from /etc/hosts
read-etc-hosts = true

# Advanced settings

# > Log level
loglevel = notify

# > Return an error page when encountering the REJECT strategy
show-error-page-for-reject = true

# > Always Real IP Hosts
always-real-ip = msftconnecttest.com, msftncsi.com, *.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com

[Replica]
hide-apple-request = 0
hide-crash-reporter-request = 1
hide-udp = 0

[Proxy]
🌐Direct = direct
🌑Proxy = ss, 1.2.3.4, 443, encrypt-method=aes-128-gcm, password=password

[Proxy Group]

🧯Fallback = fallback, 🇺🇸LosSantos
# 延迟自动测试
🕹AutoTest = url-test, 🇺🇸LosSantos

[Rule]

AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP

# Client

# Unbreak
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Unbreak.list,🌐Direct

# Advertising
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Advertising.list,REJECT
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/AdvertisingPlus.list,REJECT

# Privacy
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Privacy.list,REJECT

# Hikacking
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Hijacking.list,REJECT

# StreamingCN
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/StreamingMedia/StreamingCN,🕹AutoTest

RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Extra/Apple/Apple.list,🌐Direct

RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Extra/Microsoft/Microsoft.list,🕹AutoTest


# Local Area Network 局域网
RULE-SET,LAN,🌐Direct

# GeoIP China
GEOIP,CN,🕹AutoTest

FINAL,🌐Direct
