[General]
loglevel = warning

dns-server = 223.5.5.5, 119.29.29.29, 1.1.1.1

hijack-dns = 8.8.8.8:53,8.8.4.4:53,1.1.1.1:53,1.0.0.1:53

always-real-ip = dns.msftncsi.com, *.msftconnecttest.com, *.srv.nintendo.net, *.stun.playstation.net, stun.*, *.fbcdn.net

geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, fc00::/7, fe80::/10, localhost, *.local, *.ts.net, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn
exclude-simple-hostnames = true
read-etc-hosts = true

internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
proxy-test-udp = cp.cloudflare.com@1.1.1.1
test-timeout = 3

http-listen = 0.0.0.0:8888
socks5-listen = 0.0.0.0:8889
wifi-access-http-port = 8888
wifi-access-socks5-port = 8889
allow-wifi-access = true
proxy-restricted-to-lan = true

external-controller-access = kkchan@0.0.0.0:6170
http-api = kkchan1981@0.0.0.0:6171
http-api-web-dashboard = true

show-error-page-for-reject = false
block-quic = all-proxy
udp-policy-not-supported-behaviour = DIRECT
udp-priority = false
wifi-assist = false
ipv6 = false // 如无特殊需求不应开启 IPv6，目前网络环境下 IPv6 只会带来问题。
ipv6-vif = disabled
http-api-tls = false
all-hybrid = true
encrypted-dns-server = quic://223.5.5.5, quic://223.6.6.6, https://1.12.12.12/dns-query, https://120.53.53.53/dns-query

[Proxy]
🌐Direct = direct
🌑Proxy = ss, 1.2.3.4, 443, encrypt-method=aes-128-gcm, password=password

[Proxy Group]

🧯Fallback = fallback, 🇺🇸LosSantos
# 延迟自动测试
🕹AutoTest = url-test, 🇺🇸LosSantos

[Rule]

AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP

# Client

# Unbreak
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Unbreak.list,🌐Direct

# Advertising
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Advertising.list,REJECT
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/AdvertisingPlus.list,REJECT

# Privacy
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Privacy.list,REJECT

# Hikacking
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Guard/Hijacking.list,REJECT

# StreamingCN
RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/StreamingMedia/StreamingCN,🕹AutoTest

RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Extra/Apple/Apple.list,🌐Direct

RULE-SET,https://jkoch14.me/Profiles/Surge/Ruleset/Extra/Microsoft/Microsoft.list,🕹AutoTest


# Local Area Network 局域网
RULE-SET,LAN,🌐Direct

# GeoIP China
GEOIP,CN,🕹AutoTest

FINAL,🌐Direct
